### ISSUE TITLE
How do we identify referendums that have no number?

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#10]
The Library Parcel Tax does not have a number yet. Using the referendum number is the most straight forward way to identify a referendum (and what most humans would refer to it as). How should we identify it?

Note: that in order to be globally unique, we really identify it with the election, locality, and number.

This shows up when I'm pulling in supporting/opposing money for referendums and I noticed the slug for the Library Parcel Tax was missing.

**Comment by adborden** [comment]
I am using the slugified title of the referendum. I like that a lot, the only issue is that the names become long, and we need to reference these when linking them with the ballot. So I'm thinking of just using the slug until a number exists and then just use the number after and doing a search/replace to fix the file references. Luckily the tests should pick up on broken links so sounds okay to me.

**Comment by elinaru** [comment]
Closing - addressed. 

Interim solution is that Suzanne assigns a temporary name (ie TBD1) until a number is assigned by the registrar of voters. The registrar usually assigns a letter/number usually a week or after the ballot has been determined.
