### ISSUE TITLE
Remove June 2018 and November 2018 ballots from the side nav

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#103]
Until the Oakland June and November 2018 elections have data that we've reviewed (they currently show missing finance data), let's hide them in the nav so users are not confused.

**Comment by elinaru** [comment]
Some context: We're going to revert the sidebar to the 2016 site content until farther along. Election dates still appear in the new site design.

**Comment by anlawyer** [comment]
this is resolved by #106
