### ISSUE TITLE
Include voter's edge link on candidate page

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#111]
As a voter, I want a link on the candidate page so that I can learn more information about the candidate from an outside authroitative source.

**Comment by adborden** [comment]
The voter's edge URLs for some candidates are in the [candidate spreadsheet](https://docs.google.com/spreadsheets/d/1vJR8GR5Bk3bUQXziPiQe7to1O-QEm-_5GfD7hPjp-Xc/edit#gid=0).

**Comment by sfdoran** [comment]
@adborden did you know Voter's Edge has an API? https://votersedge.org/page/resources#developers 
Maybe we can use it to display their candidate bios and ballot summaries instead of the link or in addition to the link?

**Comment by adborden** [comment]
I did, but it's been a while since I've looked into it. I've added #122 to look into it.
