### ISSUE TITLE
Candidates running across multiple elections might show the wrong data

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#112]
We only show the candidate's latest data, so for a previous election, it will be using the current election's numbers (which is wrong).

Also, if for some reason the candidate is running in a new election, but hasn't filed, we'll show their old data in the current election.

**Comment by adborden** [comment]
@sfdoran recommended we split the candidate data by election so essentially each a canidate running in multiple elections appears isolated from other elections. You would only see the candidates data for the current election for which you are looking at. You would not be able to see all the elections a candidate has run or is running in (although that would be a feature we could build in the future).

**Comment by adborden** [comment]
@tdooner what is the state on the back end for this? The data generated for a candidate is for a single election, or is it for the candidate committee's entire lifetime? Is there a way to tell what election it was a part of (maybe `ballot_id` or `office_election`)?

**Comment by sfdoran** [comment]
@adborden we could also list other committees controlled by the candidate - the committee names essentially tell you what other elections and offices they've run for since both are required in committee names. We could also provide all the previous names of the campaign committee being used in the election.

**Comment by adborden** [comment]
@sfdoran is this information in the spreadsheet? I think trying to automate candidate name matching with the committee name might get messy.

**Comment by sfdoran** [comment]
@adborden what if we add other candidate-controlled committees to the committee spreadsheet and then add columns to associate them with the candidate similar to the ballot measures? Then could you use that to list them at the bottom of the candidate's page as "Other committees controlled by this candidate"

**Comment by adborden** [comment]
Quoting Suzanne Doran (2018-06-22 10:42:45)
> @adborden what if we add other candidate-controlled committees to the
> committee spreadsheet and then add columns to associate them with the
> candidate similar to the ballot measures? Then could you use that to
> list them at the bottom of the candidate's page as "Other committees
> controlled by this candidate"

It's a great idea! If the additional column referred to the FilerId in
the candidate sheet, that would be enough for me to put them together. I
think that's enough for the back end to calculate finances for the
committee too.


--
Aaron D Borden
Human and hacker

**Comment by sfdoran** [comment]
@adborden I can do that for Oakland. One question - how to handle candidates with more than two committees - should there be multiple columns? “com1”, “com2” etc.?

**Comment by mikeubell** [comment]
I think you can put the candidates committee id in the column in the other committee’s row.  I assume that multiple candidates cannot control one committee.

**Comment by adborden** [comment]
Yeah, I like @mikeubell 's idea. The committee should appear on the committee sheet with an additional column like "candidate_controlled_id" that refers to the candidate's committee id.

**Comment by sfdoran** [comment]
Okay I’ll try to drop those in tomorrow.

**Comment by adborden** [comment]
This is fixed because we now scope candidates to a particular election and locality.
