### ISSUE TITLE
Collect candidate photos

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#114]
Go through the [candidate spreadsheet](https://docs.google.com/spreadsheets/d/1vJR8GR5Bk3bUQXziPiQe7to1O-QEm-_5GfD7hPjp-Xc/edit#gid=0) and upload photos to google drive. If possible, try for 300px square, under 50K. Work with @elinaru to format the photos, please.

**Comment by adborden** [comment]
Once collected in the spreadsheet, we'll process them and commit them to GitHub.

**Comment by elinaru** [comment]
@sfdoran 
Candidate photos added - https://github.com/caciviclab/odca-jekyll/pull/179 (needs to be merged)
branch with files: https://github.com/caciviclab/odca-jekyll/tree/elinaru-patch-1/assets/images/candidates 

**Still missing photos for:** 
Ahmad Anderson
Benjamin M. Cohen
Shelton Dunson

**Comment by elinaru** [comment]
Photos added.
