### ISSUE TITLE
Add homepage text 

### ISSUE THREAD

**Issue by elinaru** [caciviclab/odca-jekyll#116]
Add following text to homepage: 

`<h2>Empower Oakland voters with timely, accurate, and useful information about the role of money in their local election.</h2>`

`<p>Our goal is to provide transparent non-partisan campaign contribution data in an accessible and easy to understand format. We hope this site will engage the voting public and raise awareness and accountability. Ultimately, this is one step toward shifting politics into a movement of civic engagement and ultimate citizen action.</p>`

As shown here: https://invis.io/TK8O67TEZ

**Comment by anlawyer** [comment]
WIP pull request #117 addresses this issue

**Comment by adborden** [comment]
This was completed by #117
