### ISSUE TITLE
Measure KK opposing contributors showing as "COM"

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#133]
Opposing Contributors by type shows "COM" instead of "Committees" - There is no $300 contribution listed in the contributions.

**Comment by sfdoran** [comment]
Also on Measure LL in the supporting contributors. Looks like the un-itemized contributions are being miscategorized.

**Comment by tdooner** [comment]
@mikeubell I think this is effectively "Unknown" -- the case when there are more expenditures than contributions for a ballot measure. For example, on https://caciviclab.org/odca-jekyll/referendum/oakland/2016-11-08/police-commission/ the `Coalition for Police Accountability Yes on LL` has spent $28,892 but only raised about $1.4K + $12K + $15K = $28.4K (hence the ~$400 gap).

Does that sound right?

**Comment by mikeubell** [comment]
I believe that generally organizations that were not formed specifically to support a measure can use their own funds, collected previously and theses will not be accounted for in filings.  These become unknown sources.

**Comment by adborden** [comment]
Is this still an issue?

**Comment by sfdoran** [comment]
No - it’s corrected.
