### ISSUE TITLE
Moore for Oakland City Council At-Large 2016 needs problem with data label

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#134]
Filer error is causing Moore for Oakland City Council At-Large 2016 contributions to be doubled. The total is $118K over. They put the wrong period covered date on the report so all 2016 contributions reported a second time in 2017.

**Comment by tdooner** [comment]
If it's Filer error, it seems like the easiest fix here is to use the "We know of data inaccuracies" warning and wait for the filing to be amended.

An alternative would be to try to compensate for the error in the backend, but this seems like a possibility to introduce additional error, as well as take time that we could be spending doing other things.

**Comment by sfdoran** [comment]
Yes, I agree. It needs the data inaccuracy warning.

**Comment by adborden** [comment]
ug. we lost the ability to put the "data inaccuracies" warning on specific pages. The candidate pages are autogenerated from the spreadsheet, so we'd have to add this to the spreadsheet to get this.

**Comment by adborden** [comment]
@sfdoran how does this sound?
> We are aware of an issue with the data accuracy for this filer. Contributions for 2017 were filed with the wrong period and are reported as doubled in 2016. Once the filer amends their records we'll remove this warning.

Hint: you can edit this in the spreadsheet.

**Comment by sfdoran** [comment]
@adborden I edited the notification. Hope the notification will be prominent!
