### ISSUE TITLE
Add credit to splash page photo 

### ISSUE THREAD

**Issue by elinaru** [caciviclab/odca-jekyll#143]
Credit should read: 

`Modified from source by <a href="https://www.flickr.com/photos/danramarch/4411629379/">Daniel Ramirez</a> <a href="https://creativecommons.org/licenses/by/2.0/">(CC BY 2.0)</a> 
`

**Comment by elinaru** [comment]
Should this be in the disclosure-frontend repo?

**Comment by adborden** [comment]
This is the right repo!

**Comment by adborden** [comment]
The styles for this already exist here https://github.com/caciviclab/odca-jekyll/blob/dc8318f6c6e030bb148360b480947022f68b127f/_sass/module/_hero.scss#L11, really just adding a span with a class.
