### ISSUE TITLE
Committee Contributions page parity with 2016 OD 

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#149]
- [x] Contributor search
- [x] Table sortable by contributor, amount, date
- [x] Total money raised to date above table

![image](https://user-images.githubusercontent.com/19939684/42972988-4598172a-8b66-11e8-8061-59a8b78ffab2.png)

Can we prioritize this for week of 8/13 (ballot finalized)?

**Comment by adborden** [comment]
We can try. We should create specific issues for these.

On Thu, 2018-07-19 at 15:15 -0700, Suzanne Doran <notifications@github.com> wrote:
> - Contributor search
> - Table sortable by contributor, amount, date

These ^ two require some JavaScript on the page and we haven't set that
up yet.

> - Total money raised to date above table

This ^ is already captured by
https://github.com/caciviclab/odca-jekyll/issues/11 But we need the back
end to calculate this for us.


--
Aaron D Borden
Human and Hacker

**Comment by adborden** [comment]
This work is in progress.

**Comment by ckingbailey** [comment]
resolved by #186

**Comment by adborden** [comment]
This is merged!
