### ISSUE TITLE
Add note to Desley and Aimee that they've recycled their committees

### ISSUE THREAD

**Issue by tdooner** [caciviclab/odca-jekyll#151]
We currently include data from [Desley Brooks's](https://caciviclab.org/odca-jekyll/candidate/oakland/2018-11-06/desley-brooks/) and [Aimee Eng's](https://caciviclab.org/odca-jekyll/office/oakland/2018-11-06/ousd-district-2/) previous runs for office since they recycled their committees.

Suzanne and I just agreed that we could "solve" this problem by kicking the can down the road with a disclaimer. Something along the lines of: "This page includes money raised for and spent on previous elections. [?]" with a link to an FAQ entry that explains the phenomenon in more detail.

Suzanne is going to add a column to the spreadsheet, and then we can pass that through from the backend.

**Comment by adborden** [comment]
I think the column in the spreadsheet exists... and I think you can use markdown... But if not we should allow markdown and then we could use markdown links to link to the FAQ.

**Comment by adborden** [comment]
@sfdoran which FAQ entry should this link to? Does it need to be added?

**Comment by sfdoran** [comment]
It needs to be added. I'll work on it tonight.

**Comment by mikeubell** [comment]
This will make the numbers very strange…..

**Comment by sfdoran** [comment]
@adborden I updated the message in the spreadsheet again. I want to make sure users don't misinterpret the message to suggest that filer error or noncompliance is causing the problem.
