### ISSUE TITLE
Contributor filter on committee page

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#155]
Impement a text box that performs a filter on the contributions table based on the contributor name. This should work similar to the [contributor filter from the 2016 site](http://www.opendisclosure.io/#!/committee/1388168).

Part of https://github.com/caciviclab/odca-jekyll/issues/149

**Comment by adborden** [comment]
This is tied very closely to #156, grab me if you'd like to pick this up!

**Comment by ckingbailey** [comment]
resolved by #160 and #186
