### ISSUE TITLE
Add sortable buttons in contributions table header to sort by column on committee page

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#156]
Implment clickable buttons within the contribution table header columns that toggle sorting the table based on that field (ascending and descending). This should be similar to [the sort on the 2016 site](http://www.opendisclosure.io/#!/committee/1388168).

Part of #149

**Comment by ckingbailey** [comment]
resolved by #160 and #186

**Comment by adborden** [comment]
merged!
