### ISSUE TITLE
Add "data unavailable" copy when there is no data available

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#16]
There are many places throughout the site where data doesn't show up and we get unideal behavior. Often headings with no content below it or "$0.00" repeated.

- [x] [candidate summary on ballot page](http://localhost:4000/odca-jekyll/san-francisco/)
- [x] [candidate pages](http://localhost:4000/odca-jekyll/candidate/richie-greenberg/)
- [x] [referendum page](http://localhost:4000/odca-jekyll/referendum/oakland/2018-06-05/library-parcel-tax/)

**Comment by adborden** [comment]
Moving this to v2 since the site looks broken when no data appears.

**Comment by sfdoran** [comment]
@adborden can we distinguish candidates who aren’t required to file campaign statements (campaign activity <$2000) from candidates who don’t have data because they haven’t filed a campaign statement? e.g. could we note that in the candidates’ files who don’t have a registered committee?

**Comment by adborden** [comment]
Quoting Suzanne Doran (2018-06-23 12:10:33)
> @adborden can we distinguish candidates who aren’t required to file
> campaign statements (campaign activity <$2000) from candidates who
> don’t have data because they haven’t filed a campaign statement? e.g.
> could we note that in the candidates’ files who don’t have a
> registered committee?

Sure, we need to denote that in the candidate files.

If the candidate doesn't have a registered committee, will they have a
filer id? That might be enough for us to determine the copy to display.


--
Aaron D Borden
Human and hacker

**Comment by sfdoran** [comment]
No candidates without registered committees won’t have a filer ID - they get the ID when they register the committee.

**Comment by adborden** [comment]
I think this is done. There's another issue to clean up some of the nuances with candidate reporting in https://github.com/caciviclab/odca-jekyll/issues/163
