### ISSUE TITLE
QA ballot measure data for Oakland 2016 and 2018 data

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#161]
There are some blockers here, maybe @tdooner can fill that in?

**Comment by adborden** [comment]
@mikeubell has done some work on this and @sfdoran will let us know how we stand.

**Comment by sfdoran** [comment]
@mikeubell 
Oakland Measure D - Library Parcel Tax - this one is way off - it should be $145,901 but it shows $1,678,647 supporting and $1,241,319 opposing. It looks to me like SF measure D is getting attributed to Oakland Measure D.

**Comment by sfdoran** [comment]
@mikeubell 
Hotel Employee Protections - only Times Up ID# 1403165	$336,068 and EBASE ID#1405491 should be showing up on this page. 

The other committees listed made contributions to Times Up. EBASE won't show any 460 data yet because they filed while their ID was pending. That should clear up when they amend. In the meantime, they show up as contributors to Times Up, anyway.

Question: if a committee is not a ballot measure committee, should we only enter the measures they support if they make independent expenditures? Or is that not necessary?

**Comment by sfdoran** [comment]
@mikeubell 
Oakland Children's Initiative - The Oakland Fund ID#1310647 is the primarily-formed ballot measure committee. The other committees showing expenditures all reported them as contributions to The Oakland Fund, so they should come off.

we're closest on this one. I get $909,978 in expenditures BUT  this total includes expenditures before they became a ballot measure committee for this election, so we need to figure that out.

**Comment by sfdoran** [comment]
Measure G1 - 
Two committees filed as ballot measure committees supporting G1
960997 - Friends of Oakland Public Schools
1391632 - YES ON G1, SPONSORED BY GO PUBLIC SCHOOLS ADVOCATES

Only YES ON G1, SPONSORED BY GO PUBLIC SCHOOLS ADVOCATES is showing up on the page.

Friends is in the spreadsheet but it wasn't listed as a BMC, so I updated.

**Comment by sfdoran** [comment]
Measure KK -

1391606	- Coalition to Improve Oakland Government - NO on Measure KK 

spreadsheet is up-to-date but opposed committee is not showing in expenditures

**Comment by mikeubell** [comment]
@sfdoran Re: Coalition for Police Accountability, they do not have any information in the Bal_name, Bal_num or Sup_Opp_Cd fields.

**Comment by sfdoran** [comment]
@mikeubell Also just noticed that an $2500 IE by the Oakland Police Officers Assoc opposing Pamela Price from her DA race is showing up as opposing her council race.

**Comment by mikeubell** [comment]
@sfdoran Coalition for Police Accountability is looking better now, check it out!

**Comment by sfdoran** [comment]
@mikeubell I see it! Yay! 

Now you've got to deal with Measures V & D! Are they counting sf contributions with the same letter toward the Oakland measure?

**Comment by mikeubell** [comment]
PR is pending!

**Comment by adborden** [comment]
@sfdoran gave the :+1:
