### ISSUE TITLE
Add icons to candidate bios 

### ISSUE THREAD

**Issue by elinaru** [caciviclab/odca-jekyll#170]

**Comment by elinaru** [comment]
Including twitter bird, monitor, and external link icons -- 

<img width="648" alt="screen shot 2018-08-07 at 7 35 08 pm" src="https://user-images.githubusercontent.com/6467815/43813109-15c2c5aa-9a79-11e8-92b9-dda90261f991.png">

**Comment by adborden** [comment]
SVG icons are available from font awesome:
- https://fontawesome.com/icons/desktop?style=solid
- https://fontawesome.com/icons/twitter?style=brands
- https://fontawesome.com/icons/external-link-square-alt?style=solid

**Comment by tdooner** [comment]
@aldm1995 is going to work on this; but I cannot assign it to him until he accepts the invite to the team.

**Comment by tdooner** [comment]
Hey @aldm1995, I'm going to un-assign you from this since I haven't heard from you in a little bit. Feel free to touch base and we'll find something else for you to work on!

**Comment by adborden** [comment]
I'll take a stab at this.
