### ISSUE TITLE
Update team list on About Us page 

### ISSUE THREAD

**Issue by elinaru** [caciviclab/odca-jekyll#177]
Sort "Open Disclosure Team" list into year contributed or past contributors and present list.

**Comment by elinaru** [comment]
**Current Team** 
Aaron D Borden
Tom Dooner
Suzanne Doran
Elina Rubuliak
Sarah Seiter
Mike Ubell
Alison Lawyer
Maddy Ford 
Colin King-Bailey
Jesse Woltjer


**Open Disclosure Alumni** 
Amanda Richardson
Andrell Bower
Andy Luo
Ash Roughani
Asha John
Ben Cipollini
Brian Ferrell
Daniel O’Kelly
Dave Guarino
Eddie A Tejeda
Edward Breen
Emily Ann Ramos
Emily Bookstein
Ethan Lang
Ian Rees
Ian Root
Jamie Marcus
Jesse Biroscak
Jesse Rosato
John C. Osborn
Jonathan Wrobel
Kate Drew
Klein Lieu
Kyle Warneck
Lauren Angius
Linda Peng
Luis Aguilar
Lynna Jirpongopas
Maggie Shine
Maksim Pecherskiy
Mel Restori
Michael Liu
Peter Hall
Peter Hall
Peter Thompson
Phebe Polk
Phil Wolff
Phillip Ventura
Ray Kiddy
Sam Higgins
Sean Finney
Steve 'Spike' Spiker
Sunny Juneja
Thomas Favre-Bulle
Timothy Kempf
Vivek Bansal
Vivian Brown

**Comment by elinaru** [comment]
@tdooner Am I missing anyone? ^^^

**Comment by elinaru** [comment]
Also CC @sfdoran

**Comment by tdooner** [comment]
Impressive list. I can't think of anyone offhand who should be added.

**Comment by elinaru** [comment]
Included these in https://github.com/caciviclab/odca-jekyll/pull/184
