### ISSUE TITLE
Link to current election from landing page

### ISSUE THREAD

**Issue by ckingbailey** [caciviclab/odca-jekyll#178]
currently the Follow The Money button on the landing page links to 2016 election, /office/oakland/2016-11-08/city-council-at-large/

**Comment by tdooner** [comment]
Agreed - it should go to the 2018 election by default.

**Comment by adborden** [comment]
This is blocked by https://github.com/caciviclab/odca-jekyll/issues/161

**Comment by sfdoran** [comment]
The 2018 candidate pages are okay. It's just the ballot measure pages that are having problems.

**Comment by adborden** [comment]
Merged #181
