### ISSUE TITLE
Spot check San Francisco election against SF Ethics Commission numbers

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#183]
The SF Ethics Commission keeps a dashboard of money in the SF election. We should spot check our numbers agains theirs.

**Comment by adborden** [comment]
@sfdoran when you get a chance, would you add the link to the SF Tableau dashboard?

**Comment by sfdoran** [comment]
Here it is: https://sfethics.org/ethics/2018/03/campaign-finance-dashboards-june-5-2018-and-november-6-2018-elections.html

**Comment by sfdoran** [comment]
@adborden use this to make sure campaign committees are correctly attributed to SF ballot measures:
https://data.sfgov.org/City-Management-and-Ethics/Campaign-Finance-Committee-Name-to-Measure-or-Cand/gvbz-c8jc

**Comment by adborden** [comment]
I'm moving this out of the PEC launch. I don't think that we'll get to it.

**Comment by sfdoran** [comment]
Closing since we decided to focus exclusively on Oakland.
