### ISSUE TITLE
Display candidates from most total contributions to least

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#188]
On the [office election page](https://www.opendisclosure.io/office/oakland/2018-11-06/mayor/), sort candidates with highest contributions first.

**Comment by tdooner** [comment]
Hey @anlawyer - @adborden mentioned this might be a lot easier on the backend, so I took a stab at it.

**Comment by anlawyer** [comment]
Oh awesome, thanks @tdooner!
