### ISSUE TITLE
Update referendum pages with new headings

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#189]
The existing headings on the [referendum page](https://www.opendisclosure.io/referendum/oakland/2018-11-06/hotel-employee-minimum-wage-and-workplace-protections/) are a bit confusing. Update the headings to match the [mockups](https://projects.invisionapp.com/share/TK8O67TEZ#/screens/190014315).

**Comment by sfdoran** [comment]
@jbotwins Let's talk about the headings because the calculations for the new ballot measure/referendum page are different than what's on the current page and the order is different.

**Comment by sfdoran** [comment]
@jbotwins can we get these changes in time for the PEC launch?

Change "Supporting Money" to "Contributions to Support" 
Change "Opposing Money" to "Contributions to Oppose"

![image](https://user-images.githubusercontent.com/19939684/45172976-bb0d1e80-b1bb-11e8-9360-25927bfdee54.png)

Change "Expenditures" to "Spending Breakdown by Committee"

![image](https://user-images.githubusercontent.com/19939684/45175041-3cb37b00-b1c1-11e8-9a80-bfb77d20bd11.png)

**Comment by adborden** [comment]
Ah, thanks for the clarification. My description was too ambiguous and I thought this was referring to the styling. @jbotwins can you do the copy changes first and then continue on the styling work you're doing for the headings?

**Comment by adborden** [comment]
Copy changes were done in https://github.com/caciviclab/odca-jekyll/pull/227

**Comment by adborden** [comment]
Removing this from PEC milestone, since the copy changes were completed.

**Comment by adborden** [comment]
Calling this done!
