### ISSUE TITLE
Add find my ballot widget to footer

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#199]
[Voter's Edge](https://votersedge.org/page/resources#developers) has a widget that you can embed on your site. This one allows users to find their ballot.

![screenshot from 2018-09-01 12-11-07](https://user-images.githubusercontent.com/509703/44949126-2338ba80-ade0-11e8-8412-fdadfc9ad58b.png)

**Comment by adborden** [comment]
@elinaru is the footer the right place for this?

**Comment by elinaru** [comment]
I think so. We can make the footer as high as needed. 

https://votersedge.org/page/resources#developers - How about the 240px wide look-up box

**Comment by elinaru** [comment]
![footer-desktop 2x](https://user-images.githubusercontent.com/6467815/45069029-564ca980-b07f-11e8-83f3-046bc5c8147d.png)

**Comment by elinaru** [comment]
^ How about this?

**Comment by elinaru** [comment]
Responsive mobile, ideally -- 

![footer-mobile 2x](https://user-images.githubusercontent.com/6467815/45070241-286a6380-b085-11e8-8892-bee71cd45c7e.png)

**Comment by elinaru** [comment]
Feel free to swap the "Brought to you by…" text and the Voter's Edge container as needed!

**Comment by ckingbailey** [comment]
should we _also_ credit CA Civic Lab in the "Brought to you by" ?
