### ISSUE TITLE
Add link to register to vote in California to footer

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#200]
Add a link to the footer so that users can easily find how to register to vote.

https://registertovote.ca.gov/

**Comment by elinaru** [comment]
https://votersedge.org/page/resources#developers  - How about the 240px wide look-up box

**Comment by elinaru** [comment]
We can make the footer as high as needed.

**Comment by elinaru** [comment]
See: https://github.com/caciviclab/odca-jekyll/issues/199#issuecomment-418586186

**Comment by adborden** [comment]
Fixed by #209
