### ISSUE TITLE
Contributions page doesn't work on mobile devices

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#202]
The contributions page works great on my PC, but when I look at it using my phone and tablet, the contributions list is missing.

**Comment by mikeubell** [comment]
Works on my Pixel

**Comment by anlawyer** [comment]
Contributions table doesn't show up on:
- Chrome in iPhone 6S (iOS 11.4.1)
- Safari in iPhone 6S (iOS 11.4.1)
- Safari on MacOS (10.13.4)

**Comment by adborden** [comment]
Fixed by https://github.com/caciviclab/odca-jekyll/pull/208
