### ISSUE TITLE
change "no contribs rept'd" to "candidate has raised less that $2000"

### ISSUE THREAD

**Issue by ckingbailey** [caciviclab/odca-jekyll#204]
The current language, "no contributions have been reported," sounds ambiguous, and may be misinterpreted by an uninformed reader in a way that paints the candidate in a negative light. "Candidate has raised less than $2000" is specific and alludes to the reporting laws.

**Comment by adborden** [comment]
It's supposed to be ambiguous, see the [conversation here](https://github.com/caciviclab/odca-jekyll/issues/163). There are cases where saying the candidate has raised less than $2000 is incorrect and misleading, so better to be ambiguous.
