### ISSUE TITLE
Add occupation, employer, and ZIP code to contribution tables 

### ISSUE THREAD

**Issue by elinaru** [caciviclab/odca-jekyll#210]
for all contributor tables please!

**Comment by adborden** [comment]
@mikeubell do we have this readily available?

**Comment by mikeubell** [comment]
Those columns are in the data.  We can transfer them to the contribution_list.

**Comment by adborden** [comment]
Do you want me to create an issue for that or should we just include
that as part of this issue?


--
Aaron D Borden
Human and Hacker

**Comment by mikeubell** [comment]
Open a backend issue.  I’m away for a few days and I will be more likely to,be reminded if it’s there.

**Comment by mikeubell** [comment]
> for all contributor tables please!

Not sure what you mean by "all contributor tables"

**Comment by elinaru** [comment]
> Not sure what you mean by "all contributor tables"

@mikeubell Do you mean contributor lists for candidates, ballot measures, IEC's, etc. I figured the same pattern was used on all contributor lists.

**Comment by mikeubell** [comment]
There is only one table (schedule)of contributors.

**Comment by adborden** [comment]
@elinaru should the filter behavior change? we currently only filter on name, but I could see folks wanting to filter on zipcode too. Probably not _all_ the fields.

**Comment by elinaru** [comment]
Adding zipcode to the search filter would be great. I can see an argument for allowing visitors to search for content from any column in the filter search, really. But if that's a lot more work than no need.
