### ISSUE TITLE
Update messaging on candidate contributor tables with no content

### ISSUE THREAD

**Issue by elinaru** [caciviclab/odca-jekyll#212]
CURRENT TEXT: 
Sorry, there is no contribution data available for this committee. 

PROPOSED TEXT: 
Sorry, there is no contribution data available for this committee. Note that contributor tables do not presently include loans, although funds from loans are included in the total contributions received. 

- [x] Update copy when no data is available.
- [x] Add contextual note when content does show up.
> Contributor tables do not presently include loans, although funds from loans are included in the total contributions received.

<img width="1068" alt="screen shot 2018-09-05 at 9 05 44 pm" src="https://user-images.githubusercontent.com/6467815/45134533-d3475400-b14f-11e8-828d-65baff242c1d.png">

**Comment by elinaru** [comment]
Do this before: https://github.com/caciviclab/odca-jekyll/issues/211

**Comment by sfdoran** [comment]
Small edit to proposed text:

Sorry, there is no contribution data available for this committee. Note that contributor tables do not presently include loans, although funds from loans are included in the total contributions received.

**Comment by adborden** [comment]
Should the note about loans also be displayed when the table _does_ show up? I feel like it's relevant. This would be a good contextual note, similar to how we add notes about contributions limits.

![screenshot from 2018-09-06 12-15-59](https://user-images.githubusercontent.com/509703/45179914-b2721380-b1ce-11e8-9ab5-bb86d1f069b0.png)

**Comment by sfdoran** [comment]
Yes, it works on both.

**Comment by mikeubell** [comment]
Don't know if someone wants to hit #221 when doing this.
