### ISSUE TITLE
Update contribution limit description on candidate page.

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#214]
Current description doesn't cover the higher limit for contributions from broad-based committees. May confuse users when they see contributions over $800 from qualified committees.

Change to:

The maximum contribution this candidate can accept is $800 from any individual, business entity, committee or other organization and $1,600 from a qualified broad-based committee.

**Comment by tdooner** [comment]
Hey @sfdoran , this sounds good, though it makes the header somewhat heavy.
![image](https://user-images.githubusercontent.com/129120/45258229-29dbaa80-b369-11e8-9f15-b0afcd044658.png)

How would you feel about this copy:

> The maximum contribution this candidate can receive is $800 from individuals and businesses and $1600 from qualified broad-based committees.

![image](https://user-images.githubusercontent.com/129120/45258252-568fc200-b369-11e8-8796-b22ed44b5eff.png)

**Comment by adborden** [comment]
didn't mean to reopen. I think this is addressed?
