### ISSUE TITLE
Update the "funds raised" numbers on the landing page to be inclusive of all contributions for the Oakland election

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#215]
Currently, the number represents contributions for the Oakland election, but only contributions from _within_ Oakland. So for example, it would not include contributions to the Oakland election made from out of state.

The heading should be clarified to read:
> Total contributions flowing into Oakland's 2018 Election

- [ ] Update number to be total contributions within the Oakland election
- [ ] Clarify the heading for total contributions
- [ ] Same heading and total appear on mobile.
- [ ] Verify heading is not too long with @elinaru and @sfdoran

**Comment by adborden** [comment]
@sfdoran is this the right heading?
> Total contributions for the Oakland election

**Comment by adborden** [comment]
@tdooner is there any back end work for this, or do we just need to sum the numbers in `totals.json`?

**Comment by sfdoran** [comment]
@adborden "Total contributions flowing into Oakland's 2018 Election" - too long?

**Comment by adborden** [comment]
Probably too long. But let's go with that and see how it looks.

To whoever picks this up: be sure to run it by @elinaru and @sfdoran to make sure it's not too long.

**Comment by ckingbailey** [comment]
resolved by #222
