### ISSUE TITLE
Update contribution limit tool tip text and hyperlink

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#216]
Change text to: "For more on Oakland contribution limits and campaign rules, see the Public Ethics Commission Candidate Resources page." 

Link to: https://www.oaklandca.gov/services/boards-and-commissions-index/ethics/campaign-finance-rules-and-disclosure/information-for-candidates-and-campaign-committees

We can update the FAQ and link to that in future, but right now the PEC page is the most clear.

**Comment by tdooner** [comment]
@sfdoran Can we link to this page in the tooltip instead? It's more directly relevant to giving more information than the landing page.

https://www.oaklandca.gov/services/boards-and-commissions-index/ethics/campaign-finance-rules-and-disclosure/information-for-candidates-and-campaign-committees/oakland-campaign-contribution-limits

**Comment by sfdoran** [comment]
@tdooner Yes that's fine.
