### ISSUE TITLE
Update robots.txt to allow access to Oakland elections

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#217]
We disabled the robots.txt because our data was a little wonky. Now that the Oakland elections are looking accurate, we want to be found by search engines.

We still have SF and Berkeley elections which have not been vetted, so we want to keep those disabled.

**Comment by r-i-c-h** [comment]
Is this issue closed? robots.txt doesn't have anything `oakland`, only sf/berk as per the above.
