### ISSUE TITLE
Display itemized IE supporting/opposing candidates.

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/odca-jekyll#231]
@sfdoran has requested this.  Currently we display total IE supporting/opposing candidates but not the committees that spent the money.  
This needs a design.  

The backend now generates (Total, Exp_Date, Filer_NamL, Filer_ID) tuples.

**Comment by adborden** [comment]
@elinaru do you have what you need for this?

**Comment by sfdoran** [comment]
@elinaru I was thinking of showing the IEs for candidates similar to the expenditures for ballot measures, with the heading "Spending by Third Parties (Independent Expenditures)" with the column headings "In support" and "In opposition"

![image](https://user-images.githubusercontent.com/19939684/45507569-4f8cf900-b747-11e8-9e69-000f2c16eb24.png)

**Comment by mikeubell** [comment]
The data has the Filer Name, the Date and the Amount.  Would you prefer that it just be one amount per Filer?

**Comment by sfdoran** [comment]
I’d stick with the filer name & total.
