### ISSUE TITLE
Update tool tip text in alert for committees with filings for multiple elections 

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#241]
Current text doesn't match alert. The text and link refer to the expenditure ceilings.

Suggest the following:

"After an election, a local candidate may keep their campaign account open and use leftover campaign funds for a future election for the same office by redesignating their committee for a future election."

**Comment by adborden** [comment]
@sfdoran you can change the link from within the spreadsheet.

**Comment by sfdoran** [comment]
@adborden thanks! I made the update.
