### ISSUE TITLE
Add a tool tip for Independent Expenditures

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#242]
Add an explanation of Independent Expenditures on candidate pages:
![image](https://user-images.githubusercontent.com/19939684/45655908-66a94f00-ba97-11e8-9bb9-c8f3050b171c.png)

Suggested text: 

"Spending by third parties that advocates the election or defeat of a candidate and is not made in coordination with a candidate or campaign committee is termed an independent expenditure. To learn more, see the FAQ."

**Comment by ckingbailey** [comment]
resolved by #245
