### ISSUE TITLE
Opposing commitee missing from "Spending Breakdown by Committee" list 

### ISSUE THREAD

**Issue by elinaru** [caciviclab/odca-jekyll#248]
Measure AA - Oakland Children's Initiative
https://www.opendisclosure.io/referendum/oakland/2018-11-06/oakland-children-s-initiative/big 

There is one $5k opposing contribution from an individual for this measure but it's not displayed in the "Spending Breakdown by Committee" list. Looks like a bug - can we get it back?

**Comment by elinaru** [comment]
Same thing is happening for Measures W, X, and Y -- this is a blocker IMO. Can we fix this before the launch tomorrow?

**Comment by elinaru** [comment]
Suzanne says this will be corrected when those opposing committees file spending, but I don't want wait spending to show contributing funds.

**Comment by sfdoran** [comment]
Contributions are showing because the opposing ballot measure committees are in our spreadsheet & they filed late contribution reports. The link to the committee contributions is in the expenditures part of the page, but since they haven’t reported expenditures yet there’s no link showing the committee name and linking to the contributions.

**Comment by adborden** [comment]
This doesn't look like a simple fix to me.

@tdooner @mikeubell is there an easy way to inject the supporting/opposing committees into the list even if they have no expenditures?

If we pass the suporting/opposing and election info to the front end, I can write a work around there. (playing around with this now).

**Comment by tdooner** [comment]
Yeah this is tricky. I'm looking into this. I think it's not so bad to actually just include in the list of committees for `referendum_supporting` / `referendum_opposing` any committee that has either spent or raised money. The UI will still be a little weird - it will show no expenditures, but at least the user can click through to this page:

https://www.opendisclosure.io/committee/1410941/

which has information about where the $5k came from.

**Comment by adborden** [comment]
@tdooner I've got the work-arounds above^. I'd still love to have this on the back end, but not a rush.
