### ISSUE TITLE
Need disclaimer on ballot measure page explaining calculation method

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#251]
We should note:
*In cases where there is more than one ballot measure committee, totals may included transfers between committees
*In cases where ballot measure committees are formed to support or opposed more than one measure, the committee's total  contributions & expenditures are reported for each measure.

Important that anyone who might quote the totals from those pages understand our methodology.

**Comment by ckingbailey** [comment]
Do we have text for this note @sfdoran? And are we picturing the note in the form of a tooltip?

**Comment by sfdoran** [comment]
What do you think about this text:

Data reported by committees formed to support or oppose multiple ballot measures is displayed in total and may include contributions and expenses to support or oppose other ballot measures. In cases where more than one ballot measure committee is formed to support or oppose a ballot measure, data may include transfers between committees. To view campaign statements visit Oakland’s public campaign finance portal https://public.netfile.com/pub2/Default.aspx?aid=COAK

Would that work for a tool tip? Or is there another option?

**Comment by tdooner** [comment]
That's quite a hefty tooltip! Perhaps we can add that to our FAQ page, and link to it with a tooltip that says:

"This total includes expenditures [for/against] other ballot measures. Learn about committees that [support/oppose] multiple ballot measures."

(The second sentence would link to the FAQ of course)

**Comment by ckingbailey** [comment]
Seems good @tdooner. Right now I don't see where this information would be located in the FAQ. What should the heading be, something like **How are contributions calculated for committees that support or oppose multiple measures?**
