### ISSUE TITLE
Committee East Bay Alliance appearing twice on measure Z

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#254]
https://www.opendisclosure.io/referendum/oakland/2018-11-06/hotel-employee-minimum-wage-and-workplace-protections/

![screenshot from 2018-10-01 18-14-36](https://user-images.githubusercontent.com/509703/46323987-fb3aa380-c5a5-11e8-9564-2ec93f04e39a.png)

**Comment by ckingbailey** [comment]
@tdooner @adborden Is this worth fixing on the front end, or should we wait for a backend fix?

**Comment by tdooner** [comment]
@ckingbailey We'll fix on the backend.

**Comment by mikeubell** [comment]
They filed their initial 460 with filer_id 000000.  There is no amendment to correct this.  I spose we could do some name matching to fix the ID in the data?

**Comment by adborden** [comment]
Hrmm, interesting. They both show up in the supporting_organizations list with a non-zero (identical) filer id... so somehow we know they're related.
