### ISSUE TITLE
Press page

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#256]
We want to keep track and promote anytime a researcher or journalist references Open Disclosure.

**Comment by elinaru** [comment]
Add:
All OD articles from here: https://www.openoakland.org/press/ 
and 
https://oaklandnorth.net/2018/10/10/follow-the-money-updated-website-makes-oakland-election-data-accessible/
and 
http://oaklandnewsnow.com/index.php/2018/10/05/oakland-elections-fundraising-news-thanks-to-open-disclosure-oakland/

**Comment by elinaru** [comment]
Add link to new Press page in header and footer, like so: 

<img width="1320" alt="screen shot 2018-10-16 at 8 16 48 pm" src="https://user-images.githubusercontent.com/6467815/47060013-9b84f080-d180-11e8-8997-d0466bd9af6b.png">
<img width="1322" alt="screen shot 2018-10-16 at 8 16 14 pm" src="https://user-images.githubusercontent.com/6467815/47060014-9b84f080-d180-11e8-9122-4cd5dec201ab.png">

**Comment by elinaru** [comment]
Done!
