### ISSUE TITLE
Feedback: a question on data correctness

### ISSUE THREAD

**Issue by jharrismal** [caciviclab/odca-jekyll#257]
Been trying to replicate your data for IECs for one candidate (Gary Yee) and found that your total is higher than my calculations by about $24K. I downloaded the latest spreadsheet from the Oakland Public Portal.
and found only one IEC for Yee, Families and Educators for Public Education, sponsored by GO Public Schools Advocates.

What source file do you start with?

**Comment by sfdoran** [comment]
Thanks for alerting us. Your calculation appears correct. This is a bug within our method of calculating duplicate transactions within a day of the filing deadline. Working on it now.

**Comment by jharrismal** [comment]
Thanks for looking into this. I figured that the duplicate entries were included in the total. One of my theories was that there's a *mystery* IEC I can't find listed in the file, but whose finance records appear somewhere. Data cleaning is a bear!  FYI -- I'm responsible for getting Oakland's vendor to provide a codebook to go with the export files beginning two years ago (Excel Export FAQ, Excel Export Key).

**Comment by jharrismal** [comment]
FYI -- your totals may include an IEC monetary contribution in two places: the Recipient Committee and the IEC Schedule D Expenditures. For example, $1600 donated to Gary Yee directly by Families and Educators for Public Education appears in the Schedule D Expenditures. Also, $1600 from this IEC is recorded in the candidate's recipient committee total.
My preference is to identify two separate buckets of data with no overlap: funds the candidate has raised  vs. funds spent independently by political action committees to elect the candidate.
   On Tuesday, October 2, 2018, 1:08:06 PM PDT, Suzanne Doran <notifications@github.com> wrote:  
 
 
Thanks for alerting us. Your calculation appears correct. This is a bug within our method of calculating duplicate transactions within a day of the filing deadline. Working on it now.

**Comment by tdooner** [comment]
Hi, thanks for spotting this discrepancy. Despite reviewing the data multiple times, this bug snuck past us. We've fixed it now and the changes should be live on the site soon -- if you could check back tomorrow to see if the numbers match your calculations, that would be great.

I wrote a bit more about it in case you're curious: https://github.com/caciviclab/disclosure-backend-static/pull/168

As for your point about double-counting IE's in recipient committees, thank you for the reminder! We already [filter IE committees' Schedule D Expenditures](https://github.com/caciviclab/disclosure-backend-static/blob/2b3f407399305b356c60944fdda8f841fcec260e/bin/make_view#L113-L116) to only include type 'IND' expenditures, to filter out monetary contributions and in-kind contributions that would otherwise be reported by recipient committees' Schedule A or C.

**Comment by jharrismal** [comment]
Thank you again for your speedy work.I'd be happy to check the data again tomorrow.
In addition, the documentation includes the following note and I believe it is incorrect. OEA figures were UNDER-reported by that amount ($1,191.83) not "over-reported." This is the only campaign I'm following closely, although District 6 School Board is interesting because you showed no financial reporting for the write-in candidate, Anthony Wilson, and yet he's raised more than $8,000 according to the file. "@sfdoran The bug affected two candidates that are live on the site:   
   - Clarissa Doutherd: We over-reported by $1,192 (from OAKLAND EDUCATION ASSOCIATION POLITICAL ACTION COMMITTEE)
   - Gary Yee: We over-reported by $25,871 (from Families and Educators for Public Education, Sponsored by GO Public Schools Advocates)
 


    On Tuesday, October 2, 2018, 4:09:26 PM PDT, Tom Dooner <notifications@github.com> wrote:  
 
 
Hi, thanks for spotting this discrepancy. Despite reviewing the data multiple times, this bug snuck past us. We've fixed it now and the changes should be live on the site soon -- if you could check back tomorrow to see if the numbers match your calculations, that would be great.

I wrote a bit more about it in case you're curious: caciviclab/disclosure-backend-static#168

As for your point about double-counting IE's in recipient committees, thank you for the reminder! We already filter IE committees' Schedule D Expenditures to only include type 'IND' expenditures, to filter out monetary contributions and in-kind contributions that would otherwise be reported by recipient committees' Schedule A or C.

**Comment by sfdoran** [comment]
@jharrismal Anthony Wilson's data isn't showing because he didn't enter his committee ID with the filing. That problem is impacting another candidate as well, Mya Whitaker. I'll add a warning on their pages. It will be corrected as soon as they amend their filings.

**Comment by jharrismal** [comment]
Right, Wilson's Filer I.D. is pending. Can you help me with a question I ponder: how can I quickly find out about any new IECs that may start spending to elect specific candidates?My strategy has been to do a search on the Public Portal, but then I have to open each filing to see if, for example, the IEC is spending to elect Gary Yee.
Any shortcuts would be greatly appreciated.
    On Tuesday, October 2, 2018, 4:46:01 PM PDT, Suzanne Doran <notifications@github.com> wrote:  
 
 
@jharrismal Anthony Wilson's data isn't showing because he didn't enter his committee ID with the filing. That problem is impacting another candidate as well, Mya Whitaker. I'll add a warning on their pages. It will be corrected as soon as they amend their filings.
