### ISSUE TITLE
Add public financing to candidate page

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#261]
On the Invision prototype there is a line item - "Funds from Public Financing" for the candidate pages.

I've entered the funds disbursed so far into the candidate spreadsheet column "Public Funding." If a candidate applied but was found ineligible, that is noted. One candidate didn't apply, so that is noted.

Can we get the public financing $ onto the page as "Public financing received"?

- [ ] show heading "Public financing received"
- [ ] show tooltip help linking to the PEC website
- [ ] display the amount or funding status as per mockups

**Comment by sfdoran** [comment]
Eventually candidates will report the $ on their 460s (where most of our data comes from) on Summary Line Item 14 "Miscellaneous increases to cash" - so it is not included in the contributions total. 

@mikeubell which line items do you use to calculate "Current balance"? Is Miscellaneous Increases to Cash in there?

I want to highlight the public financing, but I don't want it to be added in twice.

**Comment by sfdoran** [comment]
The prototype also shows a tool tip. Tool tip text could be:

"Eligible City Council candidates may apply for public funds to reimburse certain campaign expenses. Learn more at https://www.oaklandca.gov/topics/limited-public-financing-program ."

**Comment by adborden** [comment]
This will appear on the candidate as `public_funding_received`. It's a formatted string, so just display it as-is.

**Comment by adborden** [comment]
@sfdoran @elinaru how should we be treating these values?

"Did not apply"
"Not eligible"
"Pending approval"

What about when there is nothing in the spreadsheet, should we just not display anything or is there a default?

**Comment by sfdoran** [comment]
If it’s blank - show nothing. 

I can take out the text entries. Text doesn’t really work with the design.
