### ISSUE TITLE
List committees formed primarily to oppose candidate on candidate's page

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#262]
There are two committees formed specifically to oppose Desley Brooks. 

We should list them on her page under the heading "Committees opposing candidate", similar to the way we list other committees controlled by the candidate with a link to their contributors.

There is a column on the committees tab of our spreadsheet to indicate a non-candidate committee formed to support or oppose a candidate and the ID of the committee for the candidate in question.

**Comment by mikeubell** [comment]
The data on supporting/opposing candidates is generated:
build/_data/candidates/oakland/2018-11-06/gary-yee.json:
<snip>
  "supporting_money": {
    "contributions_received": 15550.0,
    "total_contributions": 15550.0,
    "total_expenditures": 6045.73,
    "total_loans_received": 5000.0,
    "total_supporting_independent": 56394.73,
    "support_list": [
      {
        "Total": 56394.73,
        "Filer_ID": 1409088,
        "Filer_NamL": "Families and Educators for Public Education, Sponsored by GO Public Schools Advocates"
      }
    ],
