### ISSUE TITLE
best practices

### ISSUE THREAD

**Issue by dphale** [caciviclab/odca-jekyll#266]
Hey Oakland brigade. I am new to CFA, working on a similar project with the San Jose brigade for disclosure of San Jose campaign financing data. Is there a contact person I can talk with to learn from your experience as we put together our site? Thanks - Dave Hale

**Comment by dphale** [comment]
hey there - if easier, you can email me at dhale@alumni.stanford.edu. I am interested in any page view or analytics data you have, and any feedback you have received about content from the local community - i.e. user data so we know what to focus on. Thanks, Dave

**Comment by sfdoran** [comment]
Hi Dave - I work for the City of Oakland Public Ethics Commission and work on the OD team. I'm happy to share my experience with you. We do have website analytics and we have a report from user testing we did for the 2016 version that I can share - but I'll need to dig them up. Also Open Disclosure is set-up to work for multiple jurisdictions, and we can talk about how that might work as well. My email is sdoran@oaklandca.gov if you want to get in touch.
