### ISSUE TITLE
Add Voter's Edge link to ballot measures

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#283]
The links to ballot measure analysis on Voter's Edge are in the spreadsheet if anyone wants to add them to the ballot measure pages.

- [ ] Add votersedge field to back end
- [ ] Add the votersedge url under the referendum summary

**Comment by sfdoran** [comment]
P.S. 50% of our referrals come from Voter's Edge!

**Comment by adborden** [comment]
This requires a tiny bit of back end work, probably a single line of copy/paste code.

For design, we don't really have a bio like we do on the candidate page. We'll add it underneath the summary paragraph. cc @elinaru
