### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hunterrk** [caciviclab/odca-jekyll#285]
Is it possible to access data for previous years? I'd like to see how funding on measure y compares to 2016's measure jj. Also, do you know of any similar finance breakdowns that could show me the amount of out of state opposition funding for Prop 10? 

Thanks so much!

**Comment by adborden** [comment]
Hello!

We still have 2016 data for Oakland although we don't include it in the
main navigation. We plan on bringing it back after the election. We've
tweaked our calculation methodology and can't guarantee that it is
correct at the moment.

https://www.opendisclosure.io/referendum/oakland/2016-11-08/just-cause-for-eviction-and-rent-adjustment/

We don't include anything at the state level so you'll have to get that
somewhere else. California Civic Data
Coalition[1] offers some tools to download and view data from the
Secretary of State, but as far as I know, they're not hosting it in a
way that's easy to view on a web page.

[1]: https://www.californiacivicdata.org/


--
Aaron D Borden
Human and Hacker
