### ISSUE TITLE
Feedback: a question on data correctness

### ISSUE THREAD

**Issue by TJL58** [caciviclab/odca-jekyll#286]
Hello
Thank you for your Nextdoor posting: Public Ethics Commission Sponsors Website to Show Sources of Oakland Campaign Spending for November Election.
Regarding political contributions in the OUSD District 4 School Board Seat race, the information is incomplete. Endorsed candidates benefit from well-funded campaigns in addition to their 'personally-run' campaigns. How does OpenDisclosure account for this collateral funding? Take, for example, the funding to elect Gary Yee in the amount of $102,119.60 as disclosed on California Form 496 filed 10/16/18 # VA-G18-036 
<img width="502" alt="go pac yee" src="https://user-images.githubusercontent.com/44718017/47947812-2e43c000-dee1-11e8-8a03-6c1e59fa8f82.png">
Thank you
Ms Larsen

**Comment by sfdoran** [comment]
Thanks for your question. 

Open Disclosure does show third-party spending to support & oppose candidates (independent expenditures) on the candidate’s page. 

If you scroll down, you’ll see the total independent expenditures for & against, as well as a list by committee.

It’s certainly challenging finding ways to present this information that are clear & easy to understand. We welcome your feedback/suggestions on how we might present independent expenditures in a way that’s more intuitive and less confusing.

**Comment by TJL58** [comment]
Thank you for the prompt reply. 

The presentation of the “amount collected” per candidate or measure page looks like a summary page. Independent expenditures should be shown there. Most viewers will not go further than what seems to be the ’summary’ page.

**Comment by sfdoran** [comment]
Maplight's candidate dashboard shows a bar graph for candidates with contributions and IE's in support. We might think about doing something like that as well.
