### ISSUE TITLE
Show winning candidate after election

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#287]
Here's what Voter's Edge does:
![image](https://user-images.githubusercontent.com/19939684/48292985-af470e00-e431-11e8-938d-1f9e3cf2f50b.png)

**Comment by r-i-c-h** [comment]
I can claim this. 

- Took data from http://www.acgov.org/rovresults/236/ 
- Added `is_winner` boolean column to GoogleSheets' candidates tab and added `is_approved` to the referendums tab.

**Comment by elinaru** [comment]
Can we use the term "elected" instead of "winning" here.

**Comment by anlawyer** [comment]
closed by #295
