### ISSUE TITLE
No site information description on Google?

### ISSUE THREAD

**Issue by r-i-c-h** [caciviclab/odca-jekyll#288]
Google Robots Crawling is borked? Just noticed this when googling - No Site Information is Available.
![screen shot 2018-11-13 at 6 11 52 pm](https://user-images.githubusercontent.com/19735136/48455507-539dbd00-e770-11e8-92cd-225f8397ab71.png)
(I'll reference #217 , but not really a direct relationship.)

**Comment by adborden** [comment]
@r-i-c-h can you check this again? I can't find anything in the web master tools, but kicked off a re-validation for the site, so it might be different now. If you see it again, copy the details from the "Learn why" link.
