### ISSUE TITLE
Update our system diagram that describes relationships with data sources and the front end and back end projects

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#300]

**Comment by ckingbailey** [comment]
related to issue #185

**Comment by anlawyer** [comment]
Updated: 
![Screen Shot 2020-05-26 at 8 10 46 PM](https://user-images.githubusercontent.com/28023047/82973730-05848f00-9f8d-11ea-891a-8a2771d45886.png)


See backend README as well.
