### ISSUE TITLE
Technical onboarding documentation

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#303]
At the retrospective, we talked about trying some things around our technical onboarding. Let's design an experiment and try it out.

- list of tutorials
- better description of architecture and stack
- separate doc from readme

**Comment by anlawyer** [comment]
Backend documentation: https://docs.google.com/document/d/1_GQ2f3vUTw5m1ksnQYqtpiZfPn8CTMMGT8rfUmanVsg/edit?usp=sharing

Frontend documentation:
https://docs.google.com/document/d/1scu2T_EQEl09m0QoS8uMvIGCfa3Iu8PTIyC98YjS4xg/edit?usp=sharing
