### ISSUE TITLE
Contributions page showing duplicate transactions

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#310]
@tdooner Desley Brooks' page is an example of a committee showing duplicates of the same transactions: https://www.opendisclosure.io/committee/1236617/

Mya Whitaker is another: https://www.opendisclosure.io/committee/1405266/

**Comment by ckingbailey** [comment]
This seems like a backend issue

**Comment by anlawyer** [comment]
@mikeubell looked into this, and it looks like this issue may not be relevant (or exist) anymore.

**Comment by sfdoran** [comment]
Closing. Will start a new issue if shows up in QA checks.
