### ISSUE TITLE
Verify the left nav title (date of election) is correct for 2020

### ISSUE THREAD

**Issue by anlawyer** [caciviclab/odca-jekyll#326]
Is the title of the left nav (the date of the upcoming election) static or dynamic based on the data that comes through? Will it support both March and November election dates?

**Comment by anlawyer** [comment]
@ckingbailey iirc from our sleuthing last week, this is dynamic based on the election data file. We get the election data from site data (from config.yml), then pull out the date and display it through some nested `includes` and such. 

It _should_ support both March and November, as long as we have the updated files from the backend. Does that sound right?

**Comment by ckingbailey** [comment]
Yeah, that sounds right. Remind me, the election data file you speak of, is that the same as the spreadsheet? Do we know if we need two separate spreadsheets for the two elections, March and November, this year?

**Comment by ckingbailey** [comment]
This is resolved by Suzanne having updated the spreadsheet and Tom running a fresh build
