### ISSUE TITLE
Independent Expenditures from past years are showing in 2020 candidate page

### ISSUE THREAD

**Issue by anlawyer** [caciviclab/odca-jekyll#331]
https://www.opendisclosure.io/candidate/oakland/2020-11-03/dan-kalb/
The data shown in Spending breakdown by committee in opposition of the candidate are actually from 2016. We should only be showing 2020 data.

@ckingbailey thinks this might be a frontend, where we're pulling all the data with no date filter.

**Comment by ckingbailey** [comment]
@tdooner thinks this could be because the committee in question, "Oakland Police Officer’s Association - Political Action Committee", lacks date ranges in the Open Disclosure Candidates sheet

**Comment by sfdoran** [comment]
@ckingbailey I am entering start & end dates for all the committees and for committees involved in multiple elections I will add them in for each election with start and end dates.

**Comment by ckingbailey** [comment]
This appears to have been resolved by updating the sheet
