### ISSUE TITLE
"project page" link in README is broken

### ISSUE THREAD

**Issue by ckingbailey** [caciviclab/odca-jekyll#332]
> We try to keep our [project page](http://www.caciviclab.org/opendisclosure/) up to date with all the information about how we work and where to get looped in.

That link points to github.com/caciviclab/opendisclosure, which does not exist.

What was at that URL? Is there something else we can link to here?

**Comment by anlawyer** [comment]
I think this opens a question to further discussion about the project's relationship to CA Civic Lab and how much we should link to the group. Is it dormant at the moment, or on permanent hiatus? I think we can keep in some documentation about the history of the project, but as far as I'm concerned, at this point, this is now an OpenOakland project that came out of the work started within CA Civic Lab, and we should document as such.

**Comment by anlawyer** [comment]
README has been updated and this is no longer an issue.
