### ISSUE TITLE
Update to 2020 contribution limits on candidate pages

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#333]
See:

![image](https://user-images.githubusercontent.com/19939684/73558166-7c5ab280-4407-11ea-99cb-44cffc633110.png)

For 2020, should read: 
The maximum contribution this candidate can accept is **$900** from any individual, business entity, committee or other organization and **$1,700** from a qualified broad-based committee.

If the candidate **_does not_** accept spending limits then:
The maximum contribution this candidate can accept is **$200** from any individual, business entity, committee or other organization and **$400** from a qualified broad-based committee.

**Comment by ckingbailey** [comment]
duplicate issue
