### ISSUE TITLE
Make landing page show 2020 totals

### ISSUE THREAD

**Issue by ckingbailey** [caciviclab/odca-jekyll#338]
Currently it shows 2018 total contributions. Once we're ready to debut 2020 data we need to change it to show the 2020 total.

**Comment by anlawyer** [comment]
This ticket is the frontend part of the backend ticket to create the proper totals for the new design for the landing page: https://github.com/caciviclab/disclosure-backend-static/issues/206. @joshling1919 is working on both the calculations and the design for the frontend.

**Comment by ckingbailey** [comment]
Hey @joshling1919 do you mind if I do a quick, partial resolution of this issue, just to make the landing page show the total contributions for upcoming March election? Like:
![Screen Shot 2020-02-15 at 11 44 17 AM](https://user-images.githubusercontent.com/20404311/74594227-86280c80-4fe8-11ea-8759-3783e3d90e89.png)

We need to show 2020 totals at the same as we resolve #329, which I'm working on right now.

**Comment by joshling1919** [comment]
> Hey @joshling1919 do you mind if I do a quick, partial resolution of this issue, just to make the landing page show the total contributions for upcoming March election? Like:
> ![Screen Shot 2020-02-15 at 11 44 17 AM](https://user-images.githubusercontent.com/20404311/74594227-86280c80-4fe8-11ea-8759-3783e3d90e89.png)
> 
> We need to show 2020 totals at the same as we resolve #329, which I'm working on right now.

@ckingbailey sounds good to me!

**Comment by joshling1919** [comment]
Updated design: https://projects.invisionapp.com/share/5VVJYRCRJTB#/screens/405728993

**Comment by elinaru** [comment]
Large bg image: 
![141030_0351_Oakland_City_Hall_and_Frank_Ogawa_Plaza-background](https://user-images.githubusercontent.com/6467815/75206136-8f248680-572a-11ea-9dde-5c7e2415dd59.png)
