### ISSUE TITLE
Update email alert sign-up page and confirmation email

### ISSUE THREAD

**Issue by elinaru** [caciviclab/odca-jekyll#347]
https://alert.opendisclosure.io/

**Comment by elinaru** [comment]
- remove image
- update text to include ___? What's missing?

**Comment by tdooner** [comment]
Here is the email that is automatically sent to users when they subscribe to alerts, which might be helpful inspiration for improving the Alerts copy:

______________

Hello!

On behalf of the Open Disclosure team at OpenOakland -- thank you for subscribing to our Open Disclosure Alerts! Here's what you just subscribed to:

Currently, we report the filing of all forms via the City of Oakland NetFile, although we are only currently able to extract information from a few of them (460, 497, 700). You might not receive an email every day: we'll only send one if there was at least one filing the previous day. (Between campaign cycles, we seem to be getting an email about once every three days.)

Emails will come from "Oakland Disclosure Alerts <alert@opendisclosure.io>" so you may want to add that address to your contacts so the email makes it to your inbox more reliably.

And last but not least, we want to extend an invitation for you to reply to this email with feedback on your experience on how we can make the product better. This is a constant work-in-progress for us and we want to make it as useful as possible!

Best,
Tom and the Open Disclosure Team at OpenOakland

**Comment by elinaru** [comment]
@sfdoran Posted proposals with updated language -- 
https://invis.io/APYOIOLD7SM

**Comment by sfdoran** [comment]
More forms they will get:

FPPC Form 410 - Statement of Organization
FPPC Form 496 - Late Independent Expenditure Report
FPPC Form 461 - Major Donor and. Independent Expenditure. Committee Campaign Statement
FPPC Form 803 - Behested Payment Report
Lobbyist Registration
Lobbyist Quarterly Activity Report

**Comment by sfdoran** [comment]
Subscribers receive links to disclosure reports with campaign finance information such as the officers and sponsors of political action committees active within the City of Oakland, detailed lists of campaign committee donors and other financial transactions, third-party spending on Oakland elections (independent expenditures), the economic interests declared by City officials, contributions to charitable organizations at the request of elected officials, and Oakland lobbyists activity.

**Comment by elinaru** [comment]
_Current confirmation/welcome email text:_ 
<hr>

Hello!

On behalf of the Open Disclosure team at OpenOakland -- thank you for subscribing to our Open Disclosure Alerts! Here's what you just subscribed to:

Currently, we report the filing of all forms via the [City of Oakland NetFile](https://public.netfile.com/pub2/?aid=COAK), although we are only currently able to extract information from a few of them (460, 496, 497, and 700). For the rest, you may have to click through to the original filing in order to read it.

You might not receive an email every day: we'll only send one if there was at least one filing the previous day. During the election cycle, we seem to be getting an email every other day or so. Big batches of filings tend to come in close to the [major deadlines](http://www.fppc.ca.gov/content/dam/fppc/NS-Documents/TAD/Filing%20Schedules/2020/2020_01_LCL_Nov_3_Can.pdf), which are:

**August 5** – Beginning of 24-hour 496/497 Filing (Late Independent Expenditure/Contribution Reports)
**September 24** – First Pre-Election 460 Filing (for candidates and ballot measure committees)
**October 22** – Second Pre-Election 460 Filing
**February 1, 2021** – Post-Election Semi-Annual 460 Filing

Emails will come from "Open Disclosure Alerts <[alert@opendisclosure.io]([url](alert@opendisclosure.io))>" so you may want to add that address to your contacts so the email makes it to your inbox more reliably.

And last but not least, we want to extend an invitation for you to **reply to this email with feedback on your experience** on how we can make the product better. This is a constant work-in-progress for us and we want to make it as useful as possible!

Best,
Tom and the Open Disclosure Team at [OpenOakland](https://openoakland.org/)

---
p.s. You can [unsubscribe at any time](http://alert.opendisclosure.io/alert_subscribers/XXX/edit).

**Comment by elinaru** [comment]
PROPOSED confirmation/welcome email text: https://docs.google.com/document/d/1QYrIx1cCnOf3lNCHA06qdWdb5vtx92KPWvwhqBNkknc/  

@sfdoran @tdooner  -- thoughts?

**Comment by elinaru** [comment]
Pretty sure we agreed on https://projects.invisionapp.com/share/APYOIOLD7SM#/screens/431080678 as the final choice. 
@sfdoran Correct me if I'm wrong!

**Comment by anlawyer** [comment]
Completed with https://github.com/openoakland/disclosure-alert/pull/39
