### ISSUE TITLE
Update Heading on Election Summary Page

### ISSUE THREAD

**Issue by tdooner** [caciviclab/odca-jekyll#366]
I think the heading on the Election Summary Page is wrong. On this page: https://www.opendisclosure.io/election/oakland/2020-11-03/ it reads "Data for All Upcoming Races in Oakland"

however, it should read: "Data for Oakland Election on November 3rd, 2020" or something like that.

**Comment by lukehtravis** [comment]
Went in and gave this a change @tdooner . Ready to push up a branch for review once I get repo access rights.
