### ISSUE TITLE
Update links that point to caciviclab.org

### ISSUE THREAD

**Issue by anlawyer** [caciviclab/odca-jekyll#367]
It doesn't look like the caciviclab.org website is up and running - we have broken links on our site that we need to find and fix to no longer point to the caciviclab url.

**Comment by anlawyer** [comment]
Offending link that brought up the need for this issue, the "Join us" link in the footer:
<img width="367" alt="Screen Shot 2020-05-07 at 10 29 08 AM" src="https://user-images.githubusercontent.com/28023047/81325769-b31b1700-904d-11ea-8223-fab32088e572.png">
I think this link should instead point to openoakland.org (or maybe openoakland.org/projects), since OpenOakland is where you can meet and join the team.

It might be worth going through the other links in the site, and listing them out to determine what they should be updated to, including links in the readme that reference caciviclab, before we make any changes to them. In general, pointing to openoakland.org should be fine.

**Comment by lukehtravis** [comment]
got a branch ready to push for this just waiting on push rights to the repo

**Comment by anlawyer** [comment]
Closed by #369
