### ISSUE TITLE
Add link to Alerts on candidate and referendum pages

### ISSUE THREAD

**Issue by tdooner** [caciviclab/odca-jekyll#375]
Candidate pages should say:

> Want to stay informed about this candidate? Sign up for [Open Disclosure Alerts](https://alert.opendisclosure.io) to get a daily email of election updates in your inbox.

Referendum pages should say:
> Want to stay informed about this ballot measure? Sign up for [Open Disclosure Alerts](https://alert.opendisclosure.io) to get a daily email of election updates in your inbox.

I propose we put them underneath the contributions/expenditures graphs. Also, I think it will feel most natural if the links are set to `target="_blank"` so they open in a new tab.

**Comment by lukehtravis** [comment]
Put up the following PR request implementing this fix
https://github.com/caciviclab/odca-jekyll/pull/377
