### ISSUE TITLE
Duplicate Contribution Entries in Dominguez Walton Contribution Page

### ISSUE THREAD

**Issue by dynamicMosaic** [caciviclab/odca-jekyll#385]
It appears there are 4 contributions listed by **Star Lightner** (totaling above $900) on the contribution page of [Dominguez Walton](https://www.opendisclosure.io/committee/1418926/). I'm not sure if this is a bug with the data or simply an actual excess amount of contributions from a single individual. 

![open-disclosure](https://user-images.githubusercontent.com/30738403/86964749-6d490080-c11b-11ea-947b-71e8949d8315.png)

**Comment by ckingbailey** [comment]
Hi @dynamicMosaic thanks for checking our work. If you look all the way at the bottom of that table you'll see there's a negative $400 from Star Lightner, shown as ($400), on 10/09/2019.

You can also sort the table by a column. If you sort by name it's a bit easier to see that her contributions total $900, taking into account the $400 that the campaign gave back.

I'm just now noticing there's no indication in the UI or text that the table is sortable! That's our bad.

![Screen Shot 2020-07-16 at 7 28 28 PM](https://user-images.githubusercontent.com/20404311/87742530-cb20bc80-c79b-11ea-8dd0-ec9e13a17a0b.png)
