### ISSUE TITLE
Improve formatting on search page

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/odca-jekyll#394]
The default Algolia widget does a grid.  A list will look more like our other pages.

**Comment by mikeubell** [comment]
The branch search-format contains some prototyping using a list.

**Comment by anlawyer** [comment]
This formatting update should include updates for: 
- Changing the grid layout to a list view, where each "hit" item stretches across the screen
- Overriding the base font size/font family from Algolia to more closely match the other styles on the website

Anything else to cover here?

**Comment by mikeubell** [comment]
Do we want the layout to stretch across the screen?  I was just suggesting we might.  Not sure how that will look.

**Comment by anlawyer** [comment]
> Do we want the layout to stretch across the screen? I was just suggesting we might. Not sure how that will look. Since its:
> **Lable:** data, **Lable:** data, etc.

@mikeubell Yes, isn't that the list view? The list view is different from changing the layout of the content of each "hit" item to look like a table. I was just reiterating your point above about turning the grid into the list, not saying that we should re-structure the content of the list item.

**Comment by mikeubell** [comment]
ah... ok.
