### ISSUE TITLE
Enable warning message on ballot measure committees that we have on contributor pages

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#428]
If we add text to the "data warning" column in our committee spreadsheet this appears on the contributor page:

![image](https://user-images.githubusercontent.com/19939684/96160204-7db30900-0eca-11eb-8e41-ea8f4a0638e1.png)

We want it to appear on non-candidate committee pages with data warning text, too:

![image](https://user-images.githubusercontent.com/19939684/96160334-a935f380-0eca-11eb-98ca-25013e650f31.png)

**Comment by ckingbailey** [comment]
I've started looking into this and I see that you added the data_warning to the committee's row on the spreadsheet, @sfdoran, but I'm not seeing any value at the `data_warning` key on the markdown file that is generated for Oakland Education Association Political Action Committee, 1345259. I do see that key has the expected value on the Moore for At-Large committee markdown file, 1388168. @tdooner @mikeubell I'm wondering if this is a backend issue. Is it only putting a value for the data_warning key if it's a candidate's committee?

The committee template file, committee.html, looks for the data_warning key regardless of what kind of committee it is:
(from line 20 of committee.html)
```
    {% if committee.data_warning %}
      <div class="grid grid--full grid--narrow grid--left">
        <div class="grid-col-12">
          {% include alert-message.html message=committee.data_warning %}
        </div>
      </div>
    {% endif %}
```

I'm able to display a fake data_warning locally by manually adding one to 1345259.md, so it seems like to should work if the key were populated when it gets to the frontend
![Screen Shot 2020-10-17 at 10 58 19 PM](https://user-images.githubusercontent.com/20404311/96359863-5e83c980-10cc-11eb-9eb5-cd60c306c92b.png)

**Comment by mikeubell** [comment]
@sfdoran @ckingbailey As far as I can tell this is fixed.
