### ISSUE TITLE
Feedback: a question on data correctness

### ISSUE THREAD

**Issue by preston726** [caciviclab/odca-jekyll#446]
Looks like you have the wrong website for Loren Taylor's Mayoral Campaign on his [candidate financial disclosure page ](https://www.opendisclosure.io/candidate/oakland/2022-11-08/loren-taylor/). 

The website address should be https://lorenforoakland.com/

**Comment by sfdoran** [comment]
Thanks for catching that - we'll get that corrected. Should show up on the next update.

**Comment by elinaru** [comment]
Hi! Thanks for letting me know! I'll get that fixed ASAP.

**Comment by sfdoran** [comment]
Spreadsheet updated with correct url.
