### ISSUE TITLE
URL for '?' tooltip on voluntary spending limits is broken

### ISSUE THREAD

**Issue by elinaru** [caciviclab/odca-jekyll#451]
This link needs to be updated: 
<img width="683" alt="Screen Shot 2022-09-04 at 1 45 11 PM" src="https://user-images.githubusercontent.com/6467815/188332767-6099a10a-8bf1-4a9e-a383-0a20e04da44b.png">

**Comment by sfdoran** [comment]
https://www.oaklandca.gov/resources/oakland-campaign-contribution-limits-1-1-2

**Comment by elinaru** [comment]
Done with https://github.com/caciviclab/odca-jekyll/pull/452
