### ISSUE TITLE
Display "current" elections

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/odca-jekyll#461]
Currently the landing page (index.html) displays which ever elections are specified in primary_date, general_date.  The main page (_includes/ballot-nav.html) shows elections in the current year.  Currently we have a special election this year and a general election next year so these two pages are out of sync.  We need some way to generally control what elections are displayed. 
Perhaps marking "current" elections in the elections spreadsheet?

**Comment by JoHeyJo** [comment]
Do you mean the landing page should be showing info for the primary election and special election?

**Comment by mikeubell** [comment]
Currently we only have a special election in 2023 and a general election in 2024.  The landing page is showing those (we made the special election the “primary”).  It is when you click on “follow the money” that the 2024 election is not displayed because the logic assumes both elections are in the same year.  It would be good to set which elections to display in one place and use it for both pages.
