### ISSUE TITLE
Group similar office elections in the ballot nav

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#91]
Office elections like "City Council" often run in multiple districts. We'd like to group all the districts under a 
common heading. [Mockups here](https://projects.invisionapp.com/share/TK8O67TEZ#/screens/190014309).

<img alt="screenshot from 2018-05-15 19-49-12" src="https://user-images.githubusercontent.com/509703/40093929-2df57948-5879-11e8-9e3b-7e32efdbec59.png" width="300" />

**Comment by adborden** [comment]
@jbotwins suggested we add a field to the office elections that can be used to group the related districts together.

**Comment by ckingbailey** [comment]
@adborden I was working on this last night with @jbotwins, @mford008, and Linda (whose handle I can't find on here) and we had some issues and proposed resolutions.
As you know one of the difficulties is that there's office_name attribute or anything like that on an office_elections item that we could use to sort by. Instead we tried to use Jekyll to iterate over office_elections and append a property office_name on a string contains match, like:
(Sorry, semi-pseudo-code follows coz I'm at work and don't remember the exact syntax)
```
{% for ballot_item in office_elections %}
    {% if ballot_item.title | contains "School Board' %}
        {% assign ballot_item.office_name = "School Board" %}
    {% else if ballot_item.title | contains "City Council" %}
        {% assign ballot_item.office_name = "City Council" %}
    {% endif %}
{% endfor %}
```
But on printing the results we found that we could not mutate the ballot_items of office_elections that way in a for loop. Perhaps there is a way to mutate the array prop currently being iterated over in a for loop. Do you know?
Another way we thought of is to use `| where_exp "ballot_item.title contains \"School Board\""` and the same for "City Council" to separate the School Brd and City Council items into their own separate school_board_elections and city_council_elections arrays. Then we would loop over and display each of those arrays down at the bottom of the template where we loop over the office_elections array. The annoying thing about that strategy is that then we can to either remove those values from the main office_elections array or, when we iterate over office_elections for display, skip those ballot_items that are also contained in either the school_board_elections or city_council_elections arrays.
So then that brings me to the easiest strategy, but also maybe the cheesiest. I could put a script tag at the bottom of the page with some JS that, once the ballot_nav content is loaded, grabs the rendered DOM content and inserts the "School Board" and "City Council" headings we want there.
Do you think one of these is the best solution, or is there a better way you see?

**Comment by ckingbailey** [comment]
The drawback of any of those techniques outlined above is that they only work for this election right now because the names of offices in any future election would likely be slightly different

**Comment by adborden** [comment]
Right, the best thing to do is to add an `office_name` attribute to the office elections. These recently moved out of the source code and are now generated from the [spreadsheet](https://docs.google.com/spreadsheets/d/1vJR8GR5Bk3bUQXziPiQe7to1O-QEm-_5GfD7hPjp-Xc/edit#gid=0).

@tdooner do you have any ideas for how this should be added? I started a new sheet for office_elections and getting them into the back end but not sure how we want to handle the hard-coded sorting logic. That should move to the spreadsheet, but I'm debating how it should be represented. Before we moved things to the spreadsheet, I was thinking we would have a nested list on the ballot e.g.
```yaml
office_elections:
- items:
    - mayor
- label: City Council
  items:
    - city-council-district-2
    - city-council-district-4
    - city-council-district-6
```

**Comment by tdooner** [comment]
Sure, let's update the ballot YAML to be exactly what the frontend needs. I think your structure is great.

As for the implementation, I'd like to keep the spreadsheet as simple as possible -- I wonder if we could do without adding a new tab for this. (Esp. because then it's one more thing that needs to be in-sync across sheets). Perhaps we can just make it (yet) another column on the candidates tab, say "Office Category"? As for ordering, perhaps we can just do it alphabetically?

**Comment by adborden** [comment]
I was half way through ^ before I saw this.

If we went the yaml direction, I'm not sure where we'd put it. In the spreadsheet? That would mean embedding a string with newlines and indendtation in a single cell where the formatting is probably hard to tweak.

**Comment by tdooner** [comment]
But couldn't the ballot YAML just get output by the backend, the way it already does, but instead of having a structure like:

```yaml
office_elections:
- city-council-1
- city-council-3
- city-council-5
referendums:
- referendum-1
- referendum-3
```

we update it to the structure you proposed? Or would that require too many changes in the frontend? Either way, if your PR https://github.com/caciviclab/disclosure-backend-static/pull/128 will work for the frontend, let's just go with that.

**Comment by adborden** [comment]
Oh, I see. :+1: let's go with that. I'll add that to https://github.com/caciviclab/disclosure-backend-static/pull/128, because it still lets us control the order from the spreadsheet, which I like.

**Comment by adborden** [comment]
@ckingbailey how does the above work for you?

**Comment by ckingbailey** [comment]
Looks good to me ✔️

**Comment by adborden** [comment]
I merged https://github.com/caciviclab/disclosure-backend-static/pull/128 and though it would fail the tests, but it didn't and ended up deploying with a broken nav, so I fixed it in ^ There's still some clean up to do.

**Comment by adborden** [comment]
Actually, I'm going to call this done. The styling work is covered in #92
